version: '3'

services:
  app:
    build: .
    image: dockerized-flask-app:0.1
    container_name: dockerized-flask-app
    ports:
      - 5000:5000
    environment:
      # - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_API_KEY=abcde12345
      - APP_SETTINGS=config.py
